---
## Author
author:
  name: Ниязов Санджар
  degrees: DSc
  orcid: 0000-0002-0877-7063
  email: 1032244527@pfur.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      postal-code: 117198
      city: Москва
      address: ул. Миклухо-Маклая, д. 6

## Title
title: "Шаблон отчёта по лабораторной работе"
subtitle: "Простейший вариант"
license: "CC BY"
---

# Цель работы
Целью работы является освоение процедуры оформления отчетов с помощью легковесного языка разметки Markdown


# Задание

    1. В соответствующем каталоге сделайте отчёт по лабораторной работе No 3 в формате Markdown. В качестве отчёта необходи}мо предоставить отчёты в 3 форматах: pdf, docx и md
    2. Загрузите файлы на github

# Выполнение лабораторной работы
    1. Я открыл терминал
    2. Я открыл терминал и перешёл в каталог курса сформированный при выполнении лаборатор- ной работы No3 как на рисунке и обновил локальный репозиторий, скачав изменения из удаленного репозитория с помощью команды git pull 1

# Выводы

Я освоил процедуры оформления отчетов с помощью легковесного языка разметки Markdown.

# Список литературы{.unnumbered}


